# Generated by Django 4.0.5 on 2022-07-03 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_doctor_profile_doctor_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_profile',
            old_name='doctror_degree',
            new_name='doctor_degree',
        ),
    ]
