# Generated by Django 4.0.5 on 2022-07-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_doctror_degree_doctor_profile_doctor_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profil_pic',
            field=models.ImageField(default='', upload_to='profile_pic/'),
        ),
    ]
