# Generated by Django 4.0.5 on 2022-07-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_healthprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='precription',
            field=models.TextField(default=''),
        ),
    ]
